"""Updated table names

Revision ID: 62972f64b697
Revises: 5abd5a631e41
Create Date: 2024-12-27 23:07:49.351418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62972f64b697'
down_revision = '5abd5a631e41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('characters',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('characters')
    # ### end Alembic commands ###
